# Site
repository: Kade-Yoo/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 유형민
title: Java & Kotlin Back-end Engineer
email: yhm9207@naver.com
website: https://github.com/Kade-Yoo

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: 형민-유-94812b237
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: kade-yoo
#  icon: fas fa-globe
#  url: https://github.com/Kade-Yoo
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Kotlin & Spring 기반의 4년차 백엔드 엔지니어 입니다. 
  <br>교육 기업을 다니며 청구, 결제 업무를 경험하며, 서비스 안정성을 키우는 시각과 책임감 있는 태도를 배웠습니다.
  <br>결제 데이터가 전달되지 않는 건에 대해 VAN 사와의 협업을 통해 개선을 진행하였고 월 15건 -> 1건으로 줄이게 되었습니다.
  <br>코드 측면에서도 안정성을 높이기 위한 노력을 하였습니다. 이커머스 스타트업에 입사하여 테스트 환경이 없는 상태에서 테스트 환경을 구축하여 수정으로 인한 사이드 이펙트를 줄이는데 기여하였습니다.
  <br>최근에는 일 요청 5000만건 파트너 서비스의 백엔드 엔지니어로 근무하고 있습니다.
  
  <mark>안정성을 중시하는 개발자입니다</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wemakeprice
        sub_title: Java Back-end Engineer
        caption: 2022. 09 ~ 현재
        quote: >
          Back Office Service
        description: | # this will include new lines to allow paragraphs
          - Node.js to Kotlin 이관 프로젝트
          - API Gateway 구축 프로젝트
          - 배치 환경 이관 프로젝트
      - layout: left
        title: Lific
        sub_title: Java Back-end Engineer
        caption: 2022. 05 - 2022. 07 (3개월) 07. 22 사업종료
        quote: >
          Health, Fitness, Beauty All in One Platform
        description: | # this will include new lines to allow paragraphs
          - 예약 도메인 관련 API 담당(소비자 앱, 운영자 웹, 공급자 웹)
          - 로컬 테스트 환경 구성
      - layout: left
        title: Etoos
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Web Developer
        caption: 2019. 06 - 2022. 04 (2년 11개월)
        quote: >
          Academy Homepage and Back Offic Homepage Service
        description: | # this will include new lines to allow paragraphs
          - 학생 성적, 청구, 결제(PG, VAN) 관련 백오피스 개발/운영
          - 결제 모듈 변경, 청구 및 결제 기능 고도화
          - 건당 35만건 데이터 처리 로직 개발
          - AWS 환경에서 배포 경험

  - title: Capability - Wemakeprice # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 파트너, 마케팅센터 운영 및 개발
        caption: 2022. 09 ~
        sub_title: 개발 및 운영
        quote: >
          Back Office Service
        description: | # this will include new lines to allow paragraphs
          - Node.js + Express.js로 되어있는 BackOffice Service를 Kotlin + Spring Boot로 전환하는 프로젝트 참여
          - Backoffice Service의 API 요청, 응답, 필터 등을 담당하는 API Gateway 개발
          - 프로젝트에 필요한 기술(Spring Boot, Spring Cloud, ORM, Kotlin 등)을 분석하여 적합한 기술을 찾는데 기여
          - Node.js 배치 서비스를 Jenkins로 제어하도록 하는 환경 구성
          - Git 전략 수립
          - Kotlin, Java, Node.js, Spring Boot, Spring Data JPA, QueryDSL, Spring Cloud, MySQL, Git, Jenkins

  - title: Capability - Lific # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 예약 도메인
        caption: 2022. 05 - 2022. 07
        sub_title: API 개발 담당
        quote: >
          소비자, 공급자, 운영자 예약 도메인 API
        description: | # this will include new lines to allow paragraphs
          - 예약 점심시간, 휴무일, 비정기 휴무일 기능 개발
          - 공급자 예약 도메인 API 개발
          - 로컬 테스트 환경 구성
          - Spring Boot, Spring Data JPA, QueryDSL, Spring Rest Docs, Spring Cloud, JUnit 5, H2, PostgreSQL, Git, Jenkins, k8s.

  - title: Capability - Etoos # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          title: 성적, 자습, 인강 점수에 따른 랭킹 서비스
          caption: 2022. 01 - 2022. 02
          sub_title: 랭킹 조회 및 입력 담당
          quote: >
            Spring Batch, Spring Data Redis 사용한 실시간 랭킹 서비스
          description: | # this will include new lines to allow paragraphs
            - Spring Batch를 이용한 랭킹 데이터 갱신 로직 개발
            - 점수 입력 시 랭킹 갱신 로직 개발
            - Redis를 이용한 랭킹 조회 API 개발
            - Java, Spring Boot, Spring Data Redis, Spring Batch, Spring Data JPA, QueryDSL, PostgreSQL
        - layout: left
          title: 오프라인 결제의 안정성 및 간편성 UP - VAN사 모듈 변경
          caption: 2021. 09 - 2022. 01
          sub_title: 모듈 변경, 결제 API 고도화 담당
          quote: >
            기존 결제 모듈의 결제 누락 개선과 간편 결제 기능을 위한 신규 VAN 모듈로의 변경
          description: | # this will include new lines to allow paragraphs
            - 결제 누락, 간편 결제 개선 요청을 통한 VAN사 모듈 변경
            - 결제 트래픽 분산을 위한 결제 API 서버 분리
            - Java, Spring Boot, Spring Batch, Spring Data JPA, QueryDSL, PostgreSQL, Javascript, JQuery
        - layout: left
          title: 학생별 오답에 대한 원인을 분석해주는 서비스
          caption: 2021. 05 - 2021. 08
          sub_title: 오답원인, 성적 입력, 통계 기능 개발 담당
          quote: >
            학생이 입력한 성적 및 원인 정보를 바탕으로 통계를 확인하는 서비스
          description: | # this will include new lines to allow paragraphs
            - 업로드 1회 최대 35만건에 달하는 대용량 데이터 입력 기능 개발
            - JPA, Mybatis의 대용량 처리 이슈를 JDBC를 통한 개선
            - 학생의 학원, 반별 시험 성적 및 오답원인 통계 조회 API 및 페이지 개발
            - Java, Javascript, Spring Boot, Spring MVC, Spring Data JPA, QueryDSL, Spring JDBC, Mybatis, JQuery, PostgreSQL
        - layout: left
          title: 주간별 청구 및 납부금 통계 서비스 개편
          caption: 2020. 12 - 2021. 02
          sub_title: 통계 페이지 및 API 개편 담당
          quote: >
            3개월 주기 통계 페이지 -> 일, 주, 월별 통계 페이지 개편
          description: | # this will include new lines to allow paragraphs
            - 일, 주, 월별 통계 페이지 개편을 통한 회계 처리 효율성 개선
            - Java, Javascript, Spring Boot, Spring MVC, Spring Data JPA, QueryDSL, JQuery, PostgreSQL
        - layout: left
          title: 학생정보부터 수강료 청구 및 납부를 관리하는 백오피스
          caption: 2019. 08 - 2022. 04
          sub_title: 학생, 반, 청구, 결제 관련 운영/개발 담당
          quote: >
            학생, 반, 청구, 결제 등 운영에 필요한 기능을 제공하는 서비스
          description: | # this will include new lines to allow paragraphs
            - 오프라인(VAN사), 온라인(PG사) 결제 업체와 소통하며 백오피스 결제 모듈의 안정성 확보
            - 청구 기능 리팩토링을 통한 속도개선
            - 반, 학생별 결제내역을 고도화하여 회계 처리 업무 효율성 증가(월 5건 -> 1건 미만 리소스 사용)
            - Java, Javascript, Spring Boot, Spring Batch, Spring Data JPA, QueryDSL, Mybatis, JQuery, PostgreSQL

  - title: Skill
    layout: list
    content:
      - layout: top-middle
        sub_title: 현재까지 경험했던 기술 목록을 나열하였습니다.
      - layout: left
        title : Back-End
        description: |
          - Java, Kotlin
          - Spring Boot, Spring MVC, Spring Batch, Spring Data JPA, Spring Data Redis, Spring Cloud
          - JPA, QueryDSL, Hibernate
          - Junit5, Mock
          - Gradle
          - IntelliJ
      - layout: left
        title : DevOps
        description: |
          - PostgreSQL, MySQL
          - Jenkins
          - Git, Github

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
